### ISSUE TITLE
Error in snmpwalk when raid is degraded

### ISSUE THREAD

**Issue by prezeskk** [MADhacking/snmpd-mdraid-connector#1]
I tested snmpd-mdraid-connector and when raid is active state data was sent corectly.
The output command
`snmpwalk -c public -v2c -m MD-RAID-MIB localhost mdRaidTable` was return
```
MD-RAID-MIB::mdRaidArrayIndex.1 = INTEGER: 1
MD-RAID-MIB::mdRaidArrayDev.1 = STRING: /dev/md0
MD-RAID-MIB::mdRaidArrayVersion.1 = STRING: 1.2
MD-RAID-MIB::mdRaidArrayUUID.1 = STRING: 859e995e:5018b66e:fca8b02c:42b62bf1
MD-RAID-MIB::mdRaidArrayLevel.1 = STRING: raid1
MD-RAID-MIB::mdRaidArrayLayout.1 = STRING: N/A
MD-RAID-MIB::mdRaidArrayChunkSize.1 = STRING: N/A
MD-RAID-MIB::mdRaidArraySize.1 = STRING: 1047552
MD-RAID-MIB::mdRaidArrayDeviceSize.1 = STRING: 1047552
MD-RAID-MIB::mdRaidArrayHealthOK.1 = INTEGER: true(1)
MD-RAID-MIB::mdRaidArrayHasFailedComponents.1 = INTEGER: false(2)
MD-RAID-MIB::mdRaidArrayHasAvailableSpares.1 = INTEGER: false(2)
MD-RAID-MIB::mdRaidArrayTotalComponents.1 = Gauge32: 2
MD-RAID-MIB::mdRaidArrayActiveComponents.1 = Gauge32: 2
MD-RAID-MIB::mdRaidArrayWorkingComponents.1 = Gauge32: 2
MD-RAID-MIB::mdRaidArrayFailedComponents.1 = Gauge32: 0
MD-RAID-MIB::mdRaidArraySpareComponents.1 = Gauge32: 0
MD-RAID-MIB::mdRaidArrayRaidComponents.1 = Gauge32: 2
```

> /dev/md0:
>         Version : 1.2
>   Creation Time : Mon Sep 11 19:53:08 2017
>      Raid Level : raid1
>      Array Size : 1047552 (1023.00 MiB 1072.69 MB)
>   Used Dev Size : 1047552 (1023.00 MiB 1072.69 MB)
>    Raid Devices : 2
>   Total Devices : 2
>     Persistence : Superblock is persistent
> 
>     Update Time : Mon Sep 11 22:11:20 2017
>           State : active.
>  Active Devices : 2
> Working Devices : 2
>  Failed Devices : 0
>   Spare Devices : 0
> 
>            Name : debian:0  (local to host debian)
>            UUID : 859e995e:5018b66e:fca8b02c:42b62bf1
>          Events : 40
> 
>     Number   Major   Minor   RaidDevice State
>        0       7        0        0      active sync   /dev/loop0
>        2       7        1        1      active sync   /dev/loop1

When I degrade raid matrix with command `mdadm -f `and `mdadm -r` the data was incorrect (not full)
```
MD-RAID-MIB::mdRaidArrayIndex.1 = INTEGER: 1
MD-RAID-MIB::mdRaidArrayDev.1 = STRING: /dev/md0
MD-RAID-MIB::mdRaidArrayVersion.1 = STRING: 1.2
MD-RAID-MIB::mdRaidArrayUUID.1 = STRING: 859e995e:5018b66e:fca8b02c:42b62bf1
MD-RAID-MIB::mdRaidArrayLevel.1 = STRING: raid1
MD-RAID-MIB::mdRaidArrayLayout.1 = STRING: N/A
MD-RAID-MIB::mdRaidArrayChunkSize.1 = STRING: N/A
MD-RAID-MIB::mdRaidArraySize.1 = STRING: 1047552
MD-RAID-MIB::mdRaidArrayDeviceSize.1 = STRING: 1047552
```
> /dev/md0:
>         Version : 1.2
>   Creation Time : Mon Sep 11 19:53:08 2017
>      Raid Level : raid1
>      Array Size : 1047552 (1023.00 MiB 1072.69 MB)
>   Used Dev Size : 1047552 (1023.00 MiB 1072.69 MB)
>    Raid Devices : 2
>   Total Devices : 2
>     Persistence : Superblock is persistent
> 
>     Update Time : Mon Sep 11 20:05:24 2017
>           State : active, degraded
>  Active Devices : 1 Working Devices : 1
>  Failed Devices : 1
>   Spare Devices : 0
> 
>            Name : debian:0  (local to host debian)
>            UUID : 859e995e:5018b66e:fca8b02c:42b62bf1
>          Events : 20
> 
>     Number   Major   Minor   RaidDevice State
>        0       7        0        0      active sync   /dev/loop0
>        ‐       0        0        1      removed
> 
>        1       7        1        ‐      faulty   /dev/loop1

It was not sending data `MD-RAID-MIB::mdRaidArrayHealthOK`
What is going on? How to fix it?

Testing system (with the same results):
**Debian 9.1 (armv7l SMP), kernel 4.4.79, bash 4.4.12(1)-release
Slackware 14.2 (x86_64 SMP), kernel 4.4.75, bash 4.3.46(1)-release
Slackware 12.2 (x86 SMP), kernel 2.6.38.4, bash 4.2.50(2)-release**

**Comment by HackingM** [comment]
I believe this is resolved in release 0.7, however for some reason this release had not propagated to GitHub. Please try this newer version and let me know if this resolves things for you. Sorry for any inconvenience.

**Comment by prezeskk** [comment]
I used latest versions downloaded from **https://downloads.mad-hacking.net/software**
```
hacking-bash-lib-0.2.tar.bz2
hacking-snmp-mib-0.1.tar.bz2
mdraid-snmp-mib-0.2.tar.bz2
smartctl-snmp-mib-0.3.tar.bz2
snmpd-connector-lib-0.3.tar.bz2
snmpd-mdraid-connector-0.7.tar.bz2
snmpd-smartctl-connector-0.10.1.tar.bz2
```

**Comment by prezeskk** [comment]
It looks like the script stopped executing when it encountered a degraded raid array. For two raid arrays (when second is degraded) returned data is correct for first and corrupted for second (stopped when calling `send_device_health` for degraded array). If I comment out line `FTABLE[10]="send_device_health"` the script was executed normally

**Comment by HackingM** [comment]
This should now be resolved. Please let me know if it doesn't work. Thanks!
